version: 11.3.0.{build}
image:
  - Visual Studio 2017
configuration: Release
install:
  - git submodule update --init
before_build:
  - dotnet restore
build:
  project: EDDiscovery.sln
test_script:
  - dotnet test EDDiscoveryTests\Tests.csproj
after_build:
  - cmd: copy EDDiscovery\bin\Release\net461\EDDiscovery.Portable.zip EDDiscovery.Portable.zip
artifacts:
  - path: EDDiscovery.Portable.zip
cache:
  - packages -> **\*.csproj
